### ISSUE TITLE
NPM app registry image not being polulated on deployment.yml

### ISSUE THREAD

**Issue by adamtrip** [prom3theu5/aspirational-manifests#133]
Hi there!

When deploying a NPM app the image prop on the deployment.yml is not being populated. On other services (.net API's) the image is being set.

aspire version: `8.0.0-preview.3.24105.21`
aspir8 version: `v0.1.40-preview`

`aspirate-output/fragfields-frontend/deployment.yml`
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fragfields-frontend
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: fragfields-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fragfields-frontend
    spec:
      containers:
      - name: fragfields-frontend
        image: 
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: fragfields-frontend-env
      terminationGracePeriodSeconds: 180
```
`Program.cs`
```
(...)

builder.AddNpmApp("fragfields-frontend", "../fragfields-frontend", "dev")
    .WithEndpoint(3000, 3010, scheme: "http", env: "PORT")
    .WithReference(identityService)
    .WithReference(matchService)
    .WithReference(identityService)
    .WithReference(subscriptionService)
    .AsDockerfileInManifest();

(...)
```
