### ISSUE TITLE
Dapr Error In Deployment Manifest

### ISSUE THREAD

**Issue by josephaw1022** [prom3theu5/aspirational-manifests#140]
### 🔥 Bug Description
If you are trying to generate the manifest for an aspirate application and are using dapr in that application and run `aspire generate` to build the images and create the manifest files and then run `aspirate apply` to deploy the app to your kubernetes cluster. If you go and run dapr dashboard -k, then you will see that there are no configured applications. 

### 🔍 Steps to Reproduce the Bug
1. Create a sample aspire project and add dapr to the aspire host and all that
2. add the adddaprsidecar method to the projects orchestrated by dapr
3. run aspirate init, generate, and then apply
4. run dapr dashboard -k 
5. You will see no applications in the dapr dashboard

### 🧯 Possible Solution
- Looking at the apsirate generated yaml output, specifically the deployment files, the dapr annotations are in the deployment metadata, however, looking at the [hello-kubernetes dapr quick-start tutorial ](https://github.com/dapr/quickstarts/tree/master/tutorials/hello-kubernetes), I went and looked at the deploy files that are in there and noticed that the dapr annotations are in the pods. 

so currently aspirate produces something something just like this 

```yaml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice01
  annotations:
    dapr.io/enabled: true
    dapr.io/config: tracing
    dapr.io/app-id: microservice01
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: microservice01
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: microservice01
    spec:
      containers:
      - name: microservice01
        image: docker.io/<your-dockerhub-username>/microservice01:latest
        imagePullPolicy: Always
       
```

However, the yaml file needs to look like this 

```yaml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice01
  labels:
    app: microservice01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice01
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: microservice01
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "microservice01"
        dapr.io/app-port: "8080"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: microservice01
        image: docker.io/<your-dockerhub-username>/microservice01:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: microservice01-env
      terminationGracePeriodSeconds: 180


```

once I did this, I was able to see this when I ran `dapr dashboard -k`

![image](https://github.com/prom3theu5/aspirational-manifests/assets/47674962/5d5888e0-017d-491d-827b-68334e71ac97)
