### ISSUE TITLE
Dapr sidecars not being added to docker compose

### ISSUE THREAD

**Issue by sclarke81** [prom3theu5/aspirational-manifests#166]
### 🔥 Bug Description
The docker-compose.yml produced for the AspireWithDapr sample doesn't include the sidecars. I get:

```
version: "3.8"
services:
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.6"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
    - target: 18888
      published: 18888
    - target: 18889
      published: 4317
    restart: unless-stopped
  apiservice:
    container_name: "apiservice"
    image: "localhost:5001/nmr/apiservice:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    restart: unless-stopped
  webfrontend:
    container_name: "webfrontend"
    image: "localhost:5001/nmr/webfrontend:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:4317"
    ports:
    - target: 8080
      published: 10002
    - target: 8443
      published: 10003
    restart: unless-stopped
```

Adding the following got the example working:

```
  webfrontend-dapr:
    image: "daprio/daprd:latest"
    command: [
      "./daprd",
      "-app-id", "web",
      "-app-port", "8080"
    ]
    depends_on:
      - webfrontend
    network_mode: "service:webfrontend"

  apiservice-dapr:
    image: "daprio/daprd:latest"
    command: [
      "./daprd",
      "-app-id", "api",
      "-app-port", "8080"
    ]
    depends_on:
      - apiservice
    network_mode: "service:apiservice"
```

### 🔍 Steps to Reproduce the Bug
1. Clone the AspireWithDapr sample - https://github.com/dotnet/aspire-samples/tree/main/samples/AspireWithDapr
2. Run `aspirate generate --output-format compose` in `.\AspireWithDapr\AspireWithDapr.AppHost\`
