### ISSUE TITLE
Worker services are created as deployments

### ISSUE THREAD

**Issue by TheLever** [prom3theu5/aspirational-manifests#203]
### 🔥 Bug Description
When generating yaml for deployment to a k8s cluster, worker services are created as deployments, which cause them to be recreated when they have completed. Should they not be created as Jobs?

Aspire version: 8.0.0-preview.7.24251.11
Aspirate version: 0.7.7-preview+fb3000dc28c2f82714d1aacb4bf1eb95b1892220

### 🔍 Steps to Reproduce the Bug
1. To any Aspire project, add the database-migration service
2. Build, run locally verifying the migration service finishes and is not respawned
3. Configure aspirate
4. Generate yaml using "aspirate generate"
5. Inspect the generated yaml for the migration service:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: migrate-config
  labels:
    app: migrate-config
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: migrate-config
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: migrate-config
    spec:
    ...
```

### 🧯 Possible Solution
I would assume creating a Job instead of a deployment will solve the issue. I don't think changing the strategy.type will help as it can be expected that a migration job may fail the first time.
