### ISSUE TITLE
Issue deploying Dapr Components (statestore using redis)

### ISSUE THREAD

**Issue by spicycoder** [prom3theu5/aspirational-manifests#243]
### 🔥 Bug Description
Dapr state store (redis) when deployed using aspirate, is not recognized by application's sidecar

### 🔍 Steps to Reproduce the Bug
Refer the repo: https://github.com/spicycoder/Despirate
I have a simple Aspire + Dapr application
Trying to save (and read) state into dapr state store

```cs
    [HttpPost("save")]
    public async Task<ActionResult<Product>> Save([FromBody] Product product)
    {
        logger.LogInformation("Saving product: {Product}", product);

        await daprClient.SaveStateAsync(
            "statestore",
            product.Id.ToString(),
            product);

        return Ok(product);
    }
```

I have `components/statestore.yaml`, content below

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6500
    - name: redisPassword
      value: ""
    - name: actorStateStore
      value: "true"
    - name: keyprefix
      value: none
```

And the AppHost's Program.cs file looks like

```cs
var redis = builder.AddRedis("redis", 6500);

var statestore = builder.AddDaprStateStore(
    "statestore",
    new DaprComponentOptions
    {
        LocalPath = Path.Combine("..", "components", "statestore.yaml")
    });

var api = builder
    .AddProject<Projects.AspireApp_API>("api")
    .WithDaprSidecar()
    .WithReference(statestore);
```

But `aspirate generate` produces `dapr/statestore.yaml` as below, which appears to be different from `components/statestore.yaml`

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  labels:
    app: statestore
spec:
  type: state
  version: v1
  metadata: []
```

When I perform `aspirate apply` (tried both, generated statestore.yaml as well as replacing it with content from components/statestore.yaml) The application's sidecar could not reach dapr statestore

Can someone explain if I am doing something wrong here?
Thanks
