### ISSUE TITLE
Docker Compose output is invalid

### ISSUE THREAD

**Issue by reflectronic** [prom3theu5/aspirational-manifests#301]
### 🔥 Bug Description
When generating docker-compose output for an Aspire application, the `ports` section is generated wrongly. The `docker-compose.yml` is rejected by Docker Compose.

### 🔍 Steps to Reproduce the Bug
Run the following command with Aspirate 9.0.2:

`aspirate generate --output-format compose --include-dashboard`

The `docker-compose.yml` will contain something like this:
```yaml
services:
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/aspire-dashboard:9.0"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
    - target: 18888
      published:
        port_as_int: 18888
    restart: unless-stopped
```

The `port_as_int` syntax is incorrect. It should look like:
```yml
ports:
- target: 18888
  published: "18888"
```
### 🧯 Possible Solution
This seems to be an artifact of the DockerComposeBuilder library. It seems like they have some code which [tries to do it correctly](https://github.com/aviationexam/docker-compose-builder/blob/a3bf2b8723d4b86d7e1080b5b299ab89cebfb051/src/DockerComposeBuilder/Converters/PublishedPortConverter.cs) but maybe it isn't working correctly?
