### ISSUE TITLE
Docker Compose output defines port mappings for non-external endpoints

### ISSUE THREAD

**Issue by reflectronic** [prom3theu5/aspirational-manifests#302]
### 🔥 Bug Description
When generating Docker Compose output, Aspirate defines port mappings for all bindings in the Aspire manifest, even ones that are not "external." These port mappings aren't needed, since the endpoint is not meant to be accessed externally. 

### 🔍 Steps to Reproduce the Bug
Create an Aspire project which has a Postgres database and a Web API:
```cs
var builder = DistributedApplication.CreateBuilder(args);

var pg = builder.AddPostgres("postgres");

var apiService = builder.AddProject<Projects.ApiService>("apiservice")
    .WithExternalEndpoints();
```
Then, run the following command with Aspirate 9.0.2:
```
aspirate generate --output-format compose
```

The `docker-compose.yml` will contain something like this:
```yaml
services:
  postgres:
    container_name: "postgres"
    image: "docker.io/library/postgres:17.0"
    # ...
    ports:
    - target: 5432
      published:
        port_as_int: 5432
    restart: unless-stopped
  apiservice:
    container_name: "apiservice"
    # ...
    ports:
    - target: 8080
      published:
        port_as_int: 10000
    - target: 8443
      published:
        port_as_int: 10001
    restart: unless-stopped
```

The file has a `ports` section which exposes the Web API and the Postgres database on the host using ports 10000 and 5432 respectively.

The manifest generated by Aspire will contain something like this:

```json
{
  "resources": {
    "postgres": {
      "type": "container.v0",
      "connectionString": "Host={postgres.bindings.tcp.host};Port={postgres.bindings.tcp.port};Username=postgres;Password={postgres-password.value}",
      "image": "docker.io/library/postgres:17.0",
      // ... 
      "bindings": {
        "tcp": {
          "scheme": "tcp",
          "protocol": "tcp",
          "transport": "tcp",
          "targetPort": 5432
        }
      }
    },
    "apiservice": {
      "type": "project.v0",
      // ...
      "bindings": {
        "http": {
          "scheme": "http",
          "protocol": "tcp",
          "transport": "http",
          "external": true
        },
        "https": {
          "scheme": "https",
          "protocol": "tcp",
          "transport": "http",
          "external": true
        }
      }
    }
  }
}
```

Note that the `apiservice` resource has bindings marked `"external": true`. This makes sense, since these endpoints are meant to be exposed to the internet. The `postgres` resource has bindings too, but they are not "external." This also makes sense, since the database is not meant to be exposed. But, the generated Docker Compose file exposes both of these resources on the host, which is not desired. 

### 🧯 Possible Solution
This code:
https://github.com/prom3theu5/aspirational-manifests/blob/f7ab0ac65465daec6a1cc1f6491a1e21949f3806/src/Aspirate.Shared/Extensions/ResourceExtensions.cs#L67-L75
should probably be something like `resourceWithBinding.Bindings?.Where(b => b.External).Select(...)` instead.
