### ISSUE TITLE
aspirate generate does not set image for AddNpmApp on docker compose

### ISSUE THREAD

**Issue by adamtrip** [prom3theu5/aspirational-manifests#332]
Hey there,

I was using `aspirate generate` to generate a docker-compose with a private registry. When I inspected the docker compose file it lacked the image prop for the npm app.

I've also tested with the aspire-samples Javascript project and got the same result:

```
services:
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/aspire-dashboard:9.0"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
    - target: 18888
      published: 18888
    restart: unless-stopped
  react:
    container_name: "react"
    environment:
      NODE_ENV: "development"
      services__weatherapi__http__0: "http://weatherapi:8080"
      BROWSER: "none"
      PORT: "8001"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "react"
    ports:
    - target: 8001
      published: 8001
    restart: unless-stopped
```

using aspirate version 9.1.0 with dotnet 8 and 9 (tested on both just to be sure)
